---
user_name: 'kobeep'
# hostname: "mikeeMac19"

git_modules_path: '/opt/git_modules'
rpms_dwnl_path: '/opt/rpms'

generic_pkgs:
  - ack
  - curl
  - file-roller
  - gcc
  - git
  - git-crypt
  - git-lfs
  - gnupg
  - gnupg2
  - htop
  - jq
  - nnn
  - openvpn
  - p7zip
  - pass
  - powertop
  - python3-pip
  - screen
  - sudo
  - tar
  - tmux
  - unzip
  - vim
  - wget

apt_pkgs:
  - openjdk-11-jdk
  - python3-dev
  - shellcheck

dnf_pkgs:
  - aspell-pl
  - clamav
  - edk2-ovmf
  - flatpak
  - fuse-exfat
  - hunspell-pl
  - java-11-openjdk
  - lm_sensors
  # - policycoreutils-python
  - python3-devel
  # - python3-molecule
  - python3-pip
  - redhat-rpm-config
  - setroubleshoot-server
  - ShellCheck
  - smartmontools
  - python3.11
  - cargo

dnf_gui_pkgs:
  - clamtk
  - clusterssh
  - dconf-editor
  - ddcutil
  - deluge
  - fedora-workstation-repositories
  - filezilla
  - gimp
  - gnome-shell-extension-gpaste
  - gnome-tweaks
  - gparted
  - gpaste          # Clipboard saver
  - gpaste-ui
  - kgpg            # GUI for GnuPG
  # - kodi
  # "msg": "Depsolve Error occurred: \n Problem: conflicting requests\n  - nothing provides libwayland-client++.so.0()(64bit) needed by kodi-19.4-4.fc37.x86_64\n  - nothing provides libwayland-cursor++.so.0()(64bit) needed by kodi-19.4-4.fc37.x86_64\n  - nothing provides libwayland-egl++.so.0()(64bit) needed by kodi-19.4-4.fc37.x86_64",
  - pinta
  - putty
  - remmina
  - 'remmina-plugins-*'
  - seahorse
  - vlc
  - wireshark

snap_apps: []

snap_classic_apps: []
  # - kubectl
  # - helm
  # Slack and Skype are failing on Wayland Desktop mode
  # - slack
  # - skype
  #### they are not working on fedora
  # - hollywood
  # - wallstreet

# Flatpak is better for GUI applications
flatpak_apps:
  # - name: com.valvesoftware.Steam
  #   remote: flathub
  # - name: com.skype.Client
  #   remote: flathub
  # - name: org.signal.Signal
  #   remote: flathub
  # - name: com.spotify.Client
  #   remote: flathub
  # - name: com.slack.Slack
  #   remote: flathub
  - name: com.github.debauchee.barrier
    remote: flathub
  # - name: com.discordapp.Discord
  #   remote: flathub

flatpak_repos:
  - name: flathub
    url: https://flathub.org/repo/flathub.flatpakrepo

pip_apps:
  - name: pip
    virtualenv_enabled: false
  - name: pyOpenSSL
    virtualenv_enabled: false
  - name: ansible
    virtualenv_enabled: false
  - name: argcomplete
    virtualenv_enabled: false
  - name: azure-cli
    virtualenv_enabled: true
    virtualenv_python: "python3.11"
  - name: ansible-lint
    virtualenv_enabled: true
  - name: yamllint
    virtualenv_enabled: false
  - name: psutil
    virtualenv_enabled: false
  - name: pywinrm
    virtualenv_enabled: false
  - name: niet
    virtualenv_enabled: true

gnome_extension_owner: "{{ user_name }}"
gnome_extension_path: "/home/{{ gnome_extension_owner }}/.local/share/gnome-shell/extensions/"

# https://extensions.gnome.org/extension/906/sound-output-device-chooser/
gnome_shell_extensions:
  - 517         # caffeine
  - 615         # appindicator
  - 4792        # frequency-boost-switch
  - 3193        # Blur my Shell
  - 2645        # brightness-control-using-ddcutil
  # - 906         # Sound Input & Output Device Chooser
  # - 4652        # adjust-display-brightness
  # - 1082        # cpufreq
  # - 4144        # vertical-overview
  # - 945         # cpu-power-manager
  # - 307         # dash-to-dock
  # - 1319        # GSConnect
  # - 120         # system-monitor

gnome_extension_ids: "{{ gnome_shell_extensions }}"

# https://github.com/hashicorp/terraform/releases/latest
# terraform_version: 0.14.9
# https://github.com/helm/helm/releases/latest
# helm_version: 3.5.3
# https://github.com/kubernetes/kubernetes/releases/latest
# kubectl_version: 1.20.4
# https://github.com/kubernetes-sigs/krew/releases/latest
# krew_version: 0.4.0
# https://github.com/bcicen/ctop/releases/
# ctop_version: 0.7.7
# https://github.com/gruntwork-io/terragrunt/releases/latest
# terragrunt_version: 0.31.8
# https://releases.hashicorp.com/vagrant
# vagrant_version: 2.2.19
# https://github.com/boz/kail/releases
# kail_version: 0.16.1

vscode_extensions:
  - bbenoist.vagrant
  - DavidAnson.vscode-markdownlint
  - eamodio.gitlens
  - hashicorp.terraform
  - hediet.vscode-drawio
  - ms-azure-devops.azure-pipelines
  - ms-azuretools.vscode-docker
  - ms-dotnettools.csharp
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-mssql.data-workspace-vscode
  - ms-mssql.mssql
  - ms-mssql.sql-database-projects-vscode
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-toolsai.jupyter
  - ms-toolsai.jupyter-keymap
  - ms-toolsai.jupyter-renderers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode.azure-account
  - redhat.ansible
  - redhat.vscode-commons
  - redhat.vscode-yaml
  - samuelcolvin.jinjahtml
  - streetsidesoftware.code-spell-checker
  - vscode-icons-team.vscode-icons
  - yzhang.markdown-all-in-one

# https://github.com/ishantanu/awesome-kubectl-plugins
krew_plugins:
  - sniff
  - hns
