---
- name: Get latest version of x11docker
  shell: curl -Is https://github.com/mviereck/x11docker/releases/latest | grep -i 'location:' | cut -f8 -d'/' | cut -f1 -d'"'
  register: version
  changed_when: false
  ignore_errors: true
  args:
    warn: off

- name: "Latest version of x11docker:"
  debug:
    var: version.stdout

- name: "Set fact with latest version of x11docker"
  set_fact:
    x11docker_version: "{{ version.stdout }}"
