---
- name: Get latest version
  shell: curl -Is https://github.com/bcicen/ctop/releases/latest | grep -i 'location:' | cut -f2 -d'v' | cut -f1 -d'"'
  register: version
  changed_when: false
  ignore_errors: true

- name: "Latest version of ctop:"
  debug:
    var: version.stdout

- name: "Set fact with latest version of ctop"
  set_fact:
    ctop_version: "{{ version.stdout }}"
