---
- name: Download ctop
  get_url:
    url: "https://github.com/bcicen/ctop/releases/download/v{{ ctop_version }}/ctop-{{ ctop_version }}-linux-amd64"
    dest: /usr/local/bin/ctop
    force: true
    mode: 0755
    owner: root
    group: root
