---
### Add user to nopasswd sudoers
- import_tasks: sudo.yml
# - import_tasks: hostname.yml

### Basic fedora setup
- import_tasks: firewalld.yml
# - import_tasks: selinux.yml

# - import_tasks: grub.yml

### TODO:
# qnapi
# Gnome scaling
