---
- name: Sublime repo
  shell: dnf config-manager --add-repo https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
  args:
    creates: /etc/yum.repos.d/sublime-text.repo

- name: Install latest sublime-text
  dnf:
    name: "sublime-text"
    state: present

- name: Directory for packagecontrol
  become: true
  become_user: "{{ user_name }}"
  file:
    path: "~/.config/sublime-text-3/Installed Packages"
    state: directory
    mode: 0700
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Directory for user configs
  become: true
  become_user: "{{ user_name }}"
  file:
    path: "~/.config/sublime-text-3/Packages/User"
    state: directory
    mode: 0700
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Download packagecontrol
  become: true
  become_user: "{{ user_name }}"
  get_url:
    url: "https://packagecontrol.io/Package%20Control.sublime-package"
    dest: '~/.config/sublime-text-3/Installed Packages/Package Control.sublime-package'

- name: Add sublime preferences
  become: true
  become_user: "{{ user_name }}"
  copy:
    src: Preferences.sublime-settings
    dest: ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings

- name: Add package control preferences
  become: true
  become_user: "{{ user_name }}"
  copy:
    src: Package Control.sublime-settings
    dest: ~/.config/sublime-text-3/Packages/User/Package Control.sublime-settings

- name: Add applysyntax preferences
  become: true
  become_user: "{{ user_name }}"
  copy:
    src: ApplySyntax.sublime-settings
    dest: ~/.config/sublime-text-3/Packages/User/ApplySyntax.sublime-settings
