# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: ha-mikeeq
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw

recorder:
  purge_keep_days: 90

# https://smarthomescene.com/blog/top-8-home-assistant-thermostat-cards/
lovelace:
  mode: yaml
  # Add yaml dashboards
  dashboards:
    lovelace-generated: # Needs to contain a hyphen (-)
      mode: yaml
      filename: notexist.yaml
      title: Generated
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: true
  resources:
    - url: /local/multiple-entity-row.js
      type: module

# Text to speech
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret proxy_ip      # Add the IP address of the proxy server
    - 172.16.0.0/12     # You may also provide the subnet mask, i.e.: Docker Bridge subnet

# group: !include groups.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml

# https://www.home-assistant.io/docs/configuration/splitting_configuration/#advanced-usage
automation: !include_dir_merge_list automations/

mqtt: !include mqtt.yaml
multiscrape: !include multiscrape.yaml
sensor: !include sensors.yaml
template: !include template.yaml

virtual:

switch: !include switch.yaml
climate: !include climate.yaml
