---
- name: Get latest version kubescore
  shell: curl -s https://github.com/zegl/kube-score/releases/latest  | grep 'releases/' | head -n1 | cut -f2 -d'v' | cut -d'"' -f1
  register: version
  changed_when: false
  ignore_errors: true
  args:
    warn: off

- name: "Latest version of kubescore:"
  debug:
    var: version.stdout

- name: "Set fact with latest version of kubescore"
  set_fact:
    kubescore_version: "{{ version.stdout }}"
