---
- name: Get latest version of krew
  shell: curl -Is https://github.com/kubernetes-sigs/krew/releases/latest | grep -i 'location:' | cut -f2 -d'v' | cut -f1 -d'"'
  register: version
  changed_when: false
  ignore_errors: true

- name: "Latest version of krew:"
  debug:
    var: version.stdout

- name: "Set fact with latest version of krew"
  set_fact:
    krew_version: "{{ version.stdout }}"
