# âžœ kubectl plugin list
# The following compatible plugins are available:
# /home/mikee/.krew/bin/kubectl-krew
# /home/mikee/.krew/bin/kubectl-sniff
---
- name: Upgrade krew
  include_tasks: krew/update.yml
  when: krew_version is not defined

- name: Get installed version
  become: true
  become_user: "{{ user_name }}"
  shell: ~/.krew/bin/kubectl-krew version | grep GitTag | awk '{print $2}' | cut -d'v' -f2
  register: installed_krew_version
  changed_when: false
  ignore_errors: true

- name: "Installed version of krew:"
  debug:
    var: installed_krew_version.stdout

- include_tasks: krew/get_latest_version.yml
  when: krew_version is not defined

- include_tasks: krew/install.yml
  when: installed_krew_version.stdout != krew_version

- import_tasks: krew/plugins.yml
  when: ansible_architecture != "aarch64"
