---
- name: Get latest version dive
  shell: curl -Is https://github.com/wagoodman/dive/releases/latest | grep -i 'location:' | cut -f2 -d'v' | cut -f1 -d'"'
  register: version
  changed_when: false
  ignore_errors: true
  args:
    warn: off

- name: "Latest version of dive:"
  debug:
    var: version.stdout

- name: "Set fact with latest version of dive"
  set_fact:
    dive_version: "{{ version.stdout }}"
