---
jenkins_install_path: "/opt/jenkins"
jenkins_home: "{{ jenkins_install_path }}/jenkins_home"
# UID and GID from Jenkins official docker image
jenkins_uid: "1000"
jenkins_gid: "1000"

jenkins_image_name: "jenkins:mikeeq"
jenkins_container_name: "jenkins"

jenkins_host_port: "8080"
jenkins_url: "http://localhost:{{ jenkins_host_port }}"

jenkins_users:
  - name: "jjb"
    password: "test_pass"
    email: jjb@local.jenkins
  - name: test_user
    password: test_pass2
    email: test_user@local.jenkins

jenkins_users_to_delete:
  - "testuser"
  - "admin"

jjb_username: jjb
jjb_password: "{{ jenkins_users | selectattr('name','equalto',jjb_username) | map(attribute='password') | join }}"

jenkins_admin_username: "{{ jjb_username }}"
jenkins_admin_password: "{{ jjb_password }}"

jenkins_cleanup: false
jenkins_update: false

jenkins_ssh_private_key: ""
jenkins_git_crypt_key: ""
