---
- name: Get latest version istioctl
  shell: curl -Is https://github.com/istio/istio/releases/latest  | grep -i 'location:' | cut -f8 -d'/' | cut -d'"' -f1
  register: version
  changed_when: false
  ignore_errors: true

- name: "Latest version of istioctl:"
  debug:
    var: version.stdout

- name: "Set fact with latest version of istioctl"
  set_fact:
    istioctl_version: "{{ version.stdout }}"
