---
- name: Directory for stern
  file:
    path: /tmp/stern
    state: directory

- name: Download stern
  get_url:
    url: "https://github.com/stern/stern/releases/download/v{{ stern_version }}/stern_{{ stern_version }}_linux_amd64.tar.gz"
    dest: /tmp/stern/stern.tar.gz

- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: /tmp/stern/stern.tar.gz
    dest: /tmp/stern
    remote_src: yes

- name: Copy stern
  copy:
    src: "/tmp/stern/stern"
    dest: "/usr/local/bin/stern"
    remote_src: true
    mode: 0755
    owner: root
    group: root
