---
- name: Directory for git_modules
  file:
    path: "{{ git_modules_path }}"
    state: directory
    mode: 0755
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Terminator install
  dnf:
    name: "terminator"
    state: present

# - name: Fonts
#   become: true
#   become_user: "{{ user_name }}"
#   git:
#     repo: 'https://github.com/powerline/fonts'
#     dest: "{{ git_modules_path }}/fonts"

# - name: Install Fonts
#   become: true
#   become_user: "{{ user_name }}"
#   shell: "{{ git_modules_path }}/fonts/install.sh"
#   args:
#     creates: ~/.local/share/fonts/ter-powerline-x12b.pcf.gz

- name: Directory for P10K font
  file:
    path: "~{{ user_name }}/.local/share/fonts/"
    state: directory
    mode: 0775
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: "Download Font - MesloLGS_NF_Regular"
  get_url:
    url: 'https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf'
    dest: "~{{ user_name }}/.local/share/fonts/MesloLGS_NF_Regular.ttf"
    mode: '0664'
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  register: font_download

- name: Refresh Fonts
  become: true
  become_user: "{{ user_name }}"
  shell: "fc-cache -f -v"
  when: font_download.changed

- name: Directory for terminator config
  file:
    path: "~{{ user_name }}/.config/terminator"
    state: directory
    mode: 0775
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Terminator config
  copy:
    src: terminator_config
    dest: "~{{ user_name }}/.config/terminator/config"
    mode: 0664
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    backup: true
