---
# version: '3'
services:
  homeassistant:
    container_name: homeassistant
    # https://github.com/benct/lovelace-multiple-entity-row/pull/293
    # change image tag to stable when PR above gets merged
    # image: "homeassistant/home-assistant:2023.3"
    image: "homeassistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /var/run/dbus:/run/dbus:ro
      # - /etc/localtime:/etc/localtime:ro
    restart: always
    # privileged: true
    # network_mode: host
    environment:
      # DISABLE_JEMALLOC: true
      TZ: 'Europe/Warsaw'
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - '8123:8123'
    logging:
      driver: "json-file"
      options:
        max-size: "250m"
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G
          # pids: 1
        reservations:
          cpus: 0.5
          memory: 512M
  mosquitto:
    container_name: mosquitto
    # https://hub.docker.com/_/eclipse-mosquitto
    image: "eclipse-mosquitto:2.0"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - '1883:1883'
      - '9001:9001'
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "250m"
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 256M
          # pids: 1
        reservations:
          cpus: 0.25
          memory: 64M
