---
- name: Add Visual Studio Code apt repo gpg key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
    keyring: /etc/apt/trusted.gpg.d/packages.microsoft.gpg

- name: Add Visual Studio code repository to apt
  copy:
    src: vscode.list
    dest: /etc/apt/sources.list.d/vscode.list
    owner: root
    group: root
    mode: 0644
    remote_src: true

- name: Refresh apt repos
  apt:
    update_cache: yes
